In [16]:
import numpy as np

X_raw = np.array([
    [40, 5],
    [70, 15],
    [100, 2],
])

ones = np.ones((3, 1))
X_full = np.hstack((ones, X_raw))
print(X_full)
w = np.array([[1000], [150], [-100]])

y_pred = X_full @ w
print(y_pred)

[[  1.  40.   5.]
 [  1.  70.  15.]
 [  1. 100.   2.]]
[[ 6500.]
 [10000.]
 [15800.]]
